### ISSUE TITLE
Criar dataset com rostos de criminosos famosos

### ISSUE THREAD

**Issue by keillernogueira** [keillernogueira/mp_e04#15]
Lista que pode ser util: https://www.thefamouspeople.com/criminals.php

**Comment by henriquemoc** [comment]
MOBILEFACENET/SPHEREFACE

mAP: 0.995288 top1: 1.000000 top5: 0.997959 top10: 0.988322 top20: 0.994399 top50: 0.995288 top100: 0.995288

FACENET/SPHEREFACE

mAP: 0.959841 top1: 1.000000 top5: 0.984898 top10: 0.916742 top20: 0.955553 top50: 0.959551 top100: 0.959841

CURRICULARFACE/SPHEREFACE

mAP: 1.000000 top1: 1.000000 top5: 1.000000 top10: 1.000000 top20: 1.000000 top50: 1.000000 top100: 1.000000

COSFACE/SPHEREFACE

mAP: 1.000000 top1: 1.000000 top5: 1.000000 top10: 1.000000 top20: 1.000000 top50: 1.000000 top100: 1.000000



MOBILEFACENET/MTCNN

mAP: 0.910255 top1: 1.000000 top5: 0.942619 top10: 0.834155 top20: 0.896734 top50: 0.909321 top100: 0.910255

FACENET/MTCNN

mAP: 0.989548 top1: 1.000000 top5: 0.997551 top10: 0.977334 top20: 0.987742 top50: 0.989548 top100: 0.989548

CURRICULARFACE/MTCNN

mAP: 0.986419 top1: 1.000000 top5: 0.987041 top10: 0.969093 top20: 0.986419 top50: 0.986419 top100: 0.986419

COSFACE/MTCNN

mAP: 0.999644 top1: 1.000000 top5: 1.000000 top10: 0.997959 top20: 0.999644 top50: 0.999644 top100: 0.999644

**Comment by henriquemoc** [comment]
DATASET CRIMINOSOS


PESSOA: Nº DE IMAGENS

Alexandre Nardoni: 10
Bruno(Goleiro): 10
Eike Batista: 10
Elizabeth Holmes: 10
Fernandinho Beira-Mar: 10
Laerte Patrocinio Orpinelli: 8
Osama Bin Laden: 10
Saddam Hussein: 10
Suzane Von Richthofen: 10
Ted Bundy: 10

TOTAL: 98 imagens
