### ISSUE TITLE
Indexação

### ISSUE THREAD

**Issue by keillernogueira** [keillernogueira/mp_e04#2]
Vide reunião (ata: https://docs.google.com/document/d/1umoUvAL5VkCb03qWrD80eTj8PkyAEuu1s4o2qt2769w/edit?usp=sharing), será necessário implementar a indexação na parte de reconhecimento de pessoas, dado que o MPMG planeja trabalhar com datasets com milhões de imagens.

**Comment by Fernandotnco** [comment]
Tempo em segundos da indexação para 1, 2, 5 e 10 milhões de feautures.
Testes realizados com a mobilefacenet (features de tamanho 256), e curricularface (features de tamanho 1024)

| Rede | 1M | 2M | 5M |10M |
--------|----|-----|-----|------|
|mobilefacenet| 0.215s | 0.417s | 0.952s | - |
|curricularface | 0.690s | - | - | - |
|mobilefacenet*| 0.188s | 0.592s | 1.351s | 2.668s |
|curricularface* | 0.781s | 1.522s | - | - |

'-' indica que não foi possível rodar o teste devido a falta de memória da GPU.

'*' indica que pequenas mudanças foram feitas no PyRetri para diminuir o gasto de memória.
