### ISSUE TITLE
Criar dataset

### ISSUE THREAD

**Issue by keillernogueira** [keillernogueira/mp_e04#6]
Criar dataset com as classes

armas (armas brancas e de fogo)
veículos (bicicletas, carros, ...)

Dataset possivelmente uteis: 
[Pascal Voc](http://host.robots.ox.ac.uk/pascal/VOC/)
[MS COCO](https://cocodataset.org/#home)

Frameworks possivelmente uteis:
https://github.com/wkentaro/labelme
https://github.com/jsbroks/awesome-dataset-tools#images

**Comment by keillernogueira** [comment]
- [ ] Baixar datasets do Pascal VOC e COCO
- [ ] Baixar [dataset OD-Weapon](https://github.com/ari-dasci/OD-WeaponDetection/tree/master/Weapons%20and%20similar%20handled%20objects)
- [ ] Separar imagens de interesse

**Comment by pedrohtg** [comment]
Utilidades pra possível Crawler:

- [Modulo Python](https://pypi.org/project/google_images_download/)
- [Arquivo necessário (segundo o Matheus)](https://chromedriver.chromium.org/ )
- [Exemplo de Uso](https://google-images-download.readthedocs.io/en/latest/usage.html#using-the-library-from-command-line-interface)

**Comment by pedrohtg** [comment]
Ordem de classes do dataset:
(Inserir todas nessa ordem no https://www.makesense.ai/ para fazer as anotações)

0-pistol
1-knife
2-bicycle
3-car
4-bus
5-motorbike
6-truck
7-machete
8-machine gun
9-pocket knife
10-rifle
11-sniper gun
12-stiletto knife
13-submachine gun

**Comment by henriquemoc** [comment]
Dados em Pontoise no diretório /mnt/DADOS_PONTOISE_1/datasets/mp_e04/crawler/

Nomes das labels na anotação não devem conter a numeração da ordem, mas devem estar na mesma ordem que o comentário acima. Um exemplo do correto seria:
pistol
knife
bicycle
car
...

**Comment by pedrohtg** [comment]
https://github.com/quqixun/ImageCrawler

**Comment by keillernogueira** [comment]
@pedrohtg @henriquemoc @Cogictor, coletei mais imagens das classes:

7-machete (Facão)
9-axe (machado)
11-shotgun
13-submachine gun(metralhadora leve de cano curto)

Coltei usando o Google e o Bing.

As imagens estão em:

/mnt/DADOS_PONTOISE_1/datasets/mp_e04/crawler/bing

/mnt/DADOS_PONTOISE_1/datasets/mp_e04/crawler/google


Tem 400 imagens de cada classe coletadas no google e 210 coletadas pelo bing.
A ideia eh conseguir anotar +- 500 de cada classe.
